### ISSUE TITLE
Exit YAML editor click outside textinput or press Enter shall submit

### ISSUE THREAD

**Issue by madeindjs** [DaveJarvis/scrivenvar#63]
Actually you need to press `enter` or `esc` to close textinput. I expected to close input when it loose focus (= when user click outside)

![Peek 13-08-2020 09-37](https://user-images.githubusercontent.com/11815139/90107093-9f680680-dd48-11ea-8353-10f712e9a0ac.gif)

**Comment by DaveJarvis** [comment]
I looked into this problem about a month ago. This is a wel-known bug at the JavaFX layer.

Here are some hackarounds:

* https://stackoverflow.com/a/29577624/59087
* https://stackoverflow.com/a/25291137/59087
* https://bugs.openjdk.java.net/browse/JDK-8089514
* https://github.com/kleopatra/swingempire-fx/tree/master/fx8-swingempire/src/java/de/swingempire/fx/scene/control - may have clues on how to resolve

**Comment by DaveJarvis** [comment]
Fixed in next RC.

**Comment by DaveJarvis** [comment]
Regression: pressing `Enter` does not submit.

**Comment by DaveJarvis** [comment]
Can no longer reproduce, closing until the problem reappears.
