### ISSUE TITLE
Add Definition menu with Insert and Create items

### ISSUE THREAD

**Issue by madeindjs** [DaveJarvis/scrivenvar#64]
I think variable insertion is not intuitive. IMO menu item should include an action to insert variable. This action may open a selector (like YAML editor on left side) and insert variable into editor.

**Comment by DaveJarvis** [comment]
From Ivan:

> The problem I have with the variables at the moment is because I find using my mouse while typing extremely tedious. I think it would be great if there is a way to set value to variables inside the editor e.g `$myVariable = 42$`, and after your cursor moves out of that line, you could remove the whole expression or just the assignment. Just some way to interact with the variables from inside the editor.

**Comment by DaveJarvis** [comment]
Add a definition menu that includes the following items:

* Create
* Insert

The **Create** item executes the same code as the **Create** button.

The **Insert** item attempts to execute `Ctrl+Space`.

**Comment by DaveJarvis** [comment]
Tomer writes:

> I think placing "Bold" and "Italic" under the "Insert" menu is a little weird because they're not really things you "insert". As a reference, Google Docs puts those options, and other formatting related options, under a "Format" menu.

When adding the Definition menu, also add a Format menu.

**Comment by DaveJarvis** [comment]
Fixed on mainline.
